"""hapus kolom kategori_fk di tabel kriteria

Revision ID: 383f7a081f44
Revises: 404914a64e48
Create Date: 2023-07-01 19:31:36.460900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '383f7a081f44'
down_revision = '404914a64e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.drop_constraint('kriteria_ibfk_1', type_='foreignkey')
        batch_op.drop_column('kategori_fk')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori_fk', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('kriteria_ibfk_1', 'kategori', ['kategori_fk'], ['id'])

    # ### end Alembic commands ###
