"""update tabel admin

Revision ID: 50219763f175
Revises: a7b08ea39dc4
Create Date: 2023-06-25 18:24:13.683489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50219763f175'
down_revision = 'a7b08ea39dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.drop_column('password_admin')
        batch_op.drop_column('name_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_admin', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('password_admin', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
