"""empty message

Revision ID: 86d8cac1dd19
Revises: 8446a48d118a
Create Date: 2024-07-09 03:39:53.837775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86d8cac1dd19'
down_revision = '8446a48d118a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.alter_column('brand',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.alter_column('brand',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###
