"""menambah kolom kategori_fk di tabel kriteria

Revision ID: 95c5645d1af7
Revises: d3191aace157
Create Date: 2023-07-01 19:07:15.862898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c5645d1af7'
down_revision = 'd3191aace157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('katgori_fk', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'kategori', ['katgori_fk'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('katgori_fk')

    # ### end Alembic commands ###
