"""menambah kolom ram

Revision ID: 9e4dc3bf6612
Revises: 5a4c8e1a7643
Create Date: 2023-11-13 15:20:07.469522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4dc3bf6612'
down_revision = '5a4c8e1a7643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ram', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_column('ram')

    # ### end Alembic commands ###
