"""membuat tabel kriteria

Revision ID: a623082490d7
Revises: e12be66b58c0
Create Date: 2023-06-24 22:12:42.573796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a623082490d7'
down_revision = 'e12be66b58c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kriteria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_kriteria', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kriteria')
    # ### end Alembic commands ###
