"""membuat tabel admin

Revision ID: a7b08ea39dc4
Revises: a623082490d7
Create Date: 2023-06-25 17:11:52.919916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b08ea39dc4'
down_revision = 'a623082490d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_admin', sa.String(length=100), nullable=False),
    sa.Column('password_admin', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
